# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions


name: Finantial Backend

on: [push, pull_request]

jobs:

  deploy:
    name: Deploying to Google Cloud
    runs-on: ubuntu-latest
#     needs: [unittest]
    steps:
    - name: Checkout
    - uses: actions/checkout@v2
    - name: Create app.yaml file -- setting vars
      env: # Set the secret as an input
        gcpFirebaseProjectId: ${{ secrets.GCP_FIREBASE_PROJECT_ID }}
      run: | 
        chmod +x ./deploy_scripts/backend_deploy.sh
        ./deploy_scripts/backend_deploy.sh $gcpFirebaseProjectId
    - name: Deploy to App Engine
      id: deploy
      uses: google-github-actions/deploy-appengine@v0.2.0
      with:
        deliverables: backend/app.yaml
        version: v1
        project_id: ${{ secrets.GCP_PROJECT }}
        credentials: ${{ secrets.GCP_CREDENTIALS }}

